name: Handle Issue Submission

on:
  issues:
    types:
      - labeled

jobs:
  handle-labeled-issue:
    name: Handle Labeled Issue
    if: github.event.label.name == 'new-tool-submission'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Parse Issue From
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '['
          label_marker_end: ']'

      - name: Install
        run: yarn install
      
      - name: Process
        run: yarn process '${{ steps.parse.outputs.payload }}'